Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - "db/migrate/*"

Metrics/MethodLength:
  Max: 8
  Exclude: ["db/migrate/*", "spec/**/*"]

Metrics/BlockLength:
  Exclude: ["db/migrate/*", "spec/**/*", "config/routes.rb"]

Layout/LineLength:
  Exclude:
    - "db/seeds/**/*"

Rails/Output:
  Exclude:
    - 'db/seeds/development/**/*'
    - 'db/seeds/**/*'

require: rubocop-rails
